### ISSUE TITLE
Replace NGINX with Caddy for SSL

### ISSUE THREAD

**Issue by firrae** [lo-tp/MeteorN#2]
Hey there,

This looks really interesting, but I think the SSL version would be better implemented using [Caddy Server](https://caddyserver.com/) as it automatically hooks up SSL via Let's Encrypt and renews it on a schedule for you. It might be a simpler implementation in the end.

I'm not sure if you would be interested in changing the main version of MeteorN to that, but if not I'll be forking this to work on converting the SSL version to Caddy for my own use. If you are interested in taking that one then just let me know. It'll take me a week or so to get to it myself.

**Comment by lo-tp** [comment]
Hey @firrae , 
Thanks for your reply.

I am currently working on this.
I am now trying to add `Let's Encrypt` support to `MeteorN` in the Nginx way.(Including the auto renew functionality)

If I cannot figure it out then I'll give `Caddy` a try.

**Comment by firrae** [comment]
Caddy is a bit different to use with docker, but there are a few good Docker images currently for it. I have a personal preference to Caddy as I've always found it easier to work with so that's something I'll likely do based on your existing setup. Maybe if both versions work they can be offered through this repo under different folders so people have the option? I don't think having two separate places for people to get what is essentially your design with a couple changes from myself is that great of a thing when we both want the same end goal.

**Comment by lo-tp** [comment]
Hey @firrae ,
Firstly another choice with Caddy is Definitely welcomed.

---

Secondly as you can see, I've created a new branch to implement the **let's encrypt** support.
And now I have finished.
However, I ran out of my [quota](https://letsencrypt.org/docs/rate-limits/) of issuing SSL certificates from **let's encrypt** so now it is impossible for me to test.
Without fully test, I cannot merge it into master branch.
What a pity.

**Comment by firrae** [comment]
Hi there,

Sorry for my absence on this. I've had a few major things IRL come up. I plan on completing this, though it could take a bit. I was curious if you would prefer I start a sister project called MeteorC or something akin to that though instead and we could just link to each other's project. It only clicked in my head a few days ago that MeteorN likely comes from Meteor + NGINX.

Let me know how you'd like to handle it, I'm open to either way.

**Comment by lo-tp** [comment]
A sister project named MeteorC is a good idea. 
We can go with it.
