### ISSUE TITLE
Mongo Doesn't Start in Replica Set Mode

### ISSUE THREAD

**Issue by firrae** [lo-tp/MeteorN#3]
This is an issue that will cause Meteor to work much harder since it can't connect to and read oplog monitor to see changes. In its current implementation, it resorts to polling the Mongo server which can eventually bog both the Meteor server and the Mongo server down if there are enough connections. Currently, this would be a good test platform for a small group of users, but this will not scale.

I will look at modifying your docker compose files to set up replica set and offer variants of each version that offer a 3 instance replica set. This will take me a bit though as I'm currently busy with work. I will submit a PR when I can.

**Comment by lo-tp** [comment]
Hey  @firrae

I will work on this after done with the [Let's Encrypt](https://github.com/lo-tp/MeteorN/issues/2) issue you mentioned early

**Comment by firrae** [comment]
@lo-tp I'm in no rush, my stuff won't be ready for a bit, so even if it's not ready then I'll play with it and see if I can get it working and submit something for you to look at.

**Comment by firrae** [comment]
@lo-tp this might be a good image to help solve this issue: https://hub.docker.com/r/bitnami/mongodb/ They also offer an example of setting up a full replica set via Docker Compose as well that might be useful as another option for people.

**Comment by lo-tp** [comment]
@firrae , replicate set function is nearly finished.
However one question still remains unclear to me.
That is: should we add **arbiter** to  `MONGO_URL` and `MONGO_OPG_URL` environmental variables.

**Comment by firrae** [comment]
@lo-tp In my previous experience I haven't, but I'm not sure that there is a solid reason not to.

**Comment by firrae** [comment]
Your implementation looks good to me @lo-tp, curious as to where the primary.js script gets run though? Does it need to be manually done?

**Comment by lo-tp** [comment]
It needs to be executed manually for the first time and I am trying to automate this  process(#12).

**Comment by firrae** [comment]
Ah, ok. Maybe it can be automated by running a shell script as the entry point? Start mongod and then delay a minute or more, then run the config script inside the mono shell? I'm not 100% sure how to pull that off, but I'll see if I can find a better example.
