### ISSUE TITLE
Node Version 0.10 is no longer the Meteor Version

### ISSUE THREAD

**Issue by firrae** [lo-tp/MeteorN#4]
The 1.4 update brought with it Node 4.4.7. It would likely be good to update the version of Node the containers use to run the app to be based off that version that 0.10.X which has long since been depreciated.

**Comment by firrae** [comment]
Can I ask that you open another branch for Node 4 versions, or should I send PR against your master? I will test this tonight when I get home from work to make sure it's working properly on Node 4.

**Comment by lo-tp** [comment]
I got into trouble when trying to run a Meteor app of 1.3.x on Node 4.X.
After some excrutiating debug, I found that the version of node should be set in accordance with the version of Meteor strictly in the following way strictly.
- Node 4.4.7 for Meteor 1.4.x
- Node 0.10.43 for Meteor 1.3.x and earlier

That is to say neither Node 0.10.43 nor Node 4.4.7 can work well on all Meteor versions.

So maybe it would be better to let the user decide which node version to use.

**Comment by firrae** [comment]
That's kinda my thought, if you do branches you, or I, could modify the readme to use a specific branch if they are 1.4 or pre-1.4.

**Comment by lo-tp** [comment]
Ok, let's leave master to the newest meteor version and open a new branch for pre-1.4

**Comment by firrae** [comment]
Yea, I think that's the best way. Then someone doesn't have to modify the dockerfiles and just needs to choose the correct branch. Just reduces the number of things that could go wrong.
