### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by valentinvichnal** [lo-tp/MeteorN#7]
Hi, this is a really nice idea.
But websockets don't work, there is an error during handshake.
Now that CloudFlare enabled websockets with SSL there is no point not to use it, Meteor apps are very slow without websockets.

**Comment by lo-tp** [comment]
Thank you for your reply,
Any idea on how to solver this?

**Comment by valentinvichnal** [comment]
@lo-tp I created a pull request, the Basic works fine for me now with Websockets!

I updated the SSL version too, but I'm not sure if this is enough, maybe there are additional configurations you have to add to use WSS.

I found these related questions:
http://stackoverflow.com/questions/18003689/recommended-nginx-configuration-for-meteor
http://stackoverflow.com/questions/17014969/meteor-websocket-handshake-error-400-with-nginx

I know this project aims to be lightweight and not complex, but we should add basic NGINX configurations like gzip.

**Comment by valentinvichnal** [comment]
Hi @lo-tp I created a pull request, the Basic works fine for me now with Websockets!

I updated the SSL version too, but I'm not sure if this is enough, maybe there are additional configurations you have to add to use WSS.

I found these related questions:
http://stackoverflow.com/questions/18003689/recommended-nginx-configuration-for-meteor
http://stackoverflow.com/questions/17014969/meteor-websocket-handshake-error-400-with-nginx

I know this project aims to be lightweight and not complex, but we should add basic NGINX configurations like gzip.

**Comment by lo-tp** [comment]
@valentinvichnal , I'll add Gzip to Nginx soon.
